CREATE TABLE IF NOT EXISTS user (
  id         INTEGER  PRIMARY KEY AUTOINCREMENT,
  fullname   TEXT     NOT NULL,
  email      TEXT     NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS emp (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT    NOT NULL,
  last_name  TEXT    NOT NULL
);
