name: '🚀 CD • Cloudflare • Infra Provision'
description: 'Continuous delivery workflow to provision Cloudflare infrastructure using OpenTofu v1.0.6'

on:
  workflow_dispatch:
    inputs:
      launch-cf-resources:
        type: boolean
        default: false
        description: 'Launch Cloudflare resources'
        required: true

env:
  # 🌍 Logging verbosity for OpenTofu
  TF_LOG: ERROR

  # ☁️ Cloudflare credentials
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_ZONE_ID: ${{ vars.CLOUDFLARE_ZONE_ID }}
  CLOUDFLARE_EMAIL: ${{ vars.CLOUDFLARE_EMAIL }}

jobs:
  opentofu_infra_provision:
    name: 🏗️ Tofu Cf Infra Provision
    runs-on: ubuntu-22.04
    environment: ${{ github.ref }}
    defaults:
      run:
        shell: bash
        working-directory: ./tofu

    steps:
      - name: Step - Checkout ᵛ⁵
        uses: actions/checkout@v5

      - name: Step - Get Runner Public IP Address ᵛ¹·⁰·⁰
        id: step_candidob_get-runner-ip_v1-0-0
        uses: ./.github/actions/candidob_get-runner-ip_v1-0-0
      
      - name: Step - Setup OpenTofu v1.0.6
        uses: opentofu/setup-opentofu@v1.0.6
