name: '🚀 CD • Fly.io • Deploy Ahooooy'
description: 'Continuous delivery action to provision Fly.io infrastructure and app deployment using flyctl'

# This workflow requires the following configuration in Github
#
# Variables:
#   FLY_VERSION   - Specific version of the Fly CLI to avoid unexpected changes.
#
# Secrets:
#   FLY_API_TOKEN - Authentication token used to interact with Fly.io's API or CLI

on:
  workflow_dispatch:
    inputs:
      fly_app_name:
        type: string
        default: ahooooy
        description: 'Unique Fly.io App name'
        required: true
      fly_app_create:
        type: boolean
        default: false
        description: 'Create Fly.io App'
        required: false
      build_push_go_artifact:
        type: boolean
        default: false
        description: 'Build and Push Go Artifact'
        required: false
      fly_app_update:
        type: boolean
        default: false
        description: 'Deploy Fly.io App'
        required: false

permissions:
  contents: write

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_VERSION: ${{ vars.FLY_VERSION  || '0.3.167' }}
  APP: ${{ inputs.fly_app_name }}
  ORG: ${{ vars.FLY_ORG || 'personal' }}
  REGION: ${{ vars.FLY_REGION || 'bom' }}

jobs:
  job_fly_app_create:
    name: 🪂 Fly App Creation
    if: ${{ inputs.fly_app_create }}
    runs-on: ubuntu-22.04
    env:
      VM_NAME: 'go-fiber-vm'
      VOLUME: 'go_fiber_vol'
    defaults:
      run:
        shell: bash
    steps:
      - name: Step - Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: '${{ github.repository }}'
          token: '${{ github.token }}'
      - name: Step - flyctl Setup ᵛ⁰·³·¹⁶⁷
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLY_VERSION }}
      - name: Step - Create Fly.io App
        run: |
          if ! flyctl apps list --org="$ORG" --json | jq -e --arg app "$APP" 'any(.[]; .Name == $app or .name == $app)' >/dev/null; then
            flyctl apps create --name="$APP" --org="$ORG" --yes
          fi
      - name: Step - Create Fly.io Volume
        run: |
          if ! flyctl volumes list --app="$APP" --json | jq -e 'any(.[]; .id != null and .id != "")' >/dev/null; then
            VOLUME_ID=$(flyctl volumes create $VOLUME --app="$APP" --count=1 --no-encryption --region="$REGION" --require-unique-zone=true --size=1 --snapshot-retention=1 --vm-size='shared-cpu-1x' --yes --json | jq -r '.id')
          fi
          VOLUME_ID=${VOLUME_ID:-$(flyctl volumes list --app="$APP" --json | jq -r '.[0].id')}
          echo "VOLUME_ID=$VOLUME_ID" >> $GITHUB_ENV
      - name: Step - Launch Fly.io Machine
        env:
          IMAGE: docker.io/balajipothula/mini_httpd:1.30-r5
        run: |
          if ! flyctl machines list --app="$APP" --json | jq -e --arg name "$VM_NAME" 'any(.[]; .name == $name)' >/dev/null; then
            flyctl machine run $IMAGE --app="$APP" --name="$VM_NAME" --org="$ORG" --port='443:80/tcp:http:tls' --region="$REGION" --use-zstd --vm-size='shared-cpu-1x' --volume="$VOLUME_ID:/gofiber:rw" --wg=true
          fi
      - name: Step - Allocate IPv4 to Fly.io Machine
        run: |
          if ! flyctl ips list --app="$APP" --json | jq -e 'any(.[]; .Address != null and .Address != "")' >/dev/null; then
            flyctl ips allocate-v4 --app="$APP" --region="$REGION" --shared --yes
          fi
  job_build_push_go_artifact:
    name: 🐹 Build & Push Go Artifact
    needs: [job_fly_app_create]
    if: ${{ inputs.build_push_go_artifact }}
    runs-on: ubuntu-22.04
    outputs:
      artifact: ${{ steps.build_n_compress.outputs.artifact }}
    steps:
      - name: Step - Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: '${{ github.repository }}'
          token: '${{ github.token }}'
      - name: Step - Setup Go Environment ᵛ⁵
        uses: ./.github/actions/setup-go_v5
        with:
          go-version: '1.21.0'
          token: '${{ github.token }}'
          cache-dependency-path: go/go.sum
      - name: Step - Build & Compress Go Artifact
        id: build_n_compress
        working-directory: go
        run: make compress
      - name: Step - Upload Go Artifact ᵛ⁴
        uses: ./.github/actions/upload-artifact_v4
        env:
          ARTIFACT: ${{ steps.build_n_compress.outputs.artifact }}
        with:
          name: ${{ env.ARTIFACT }}
          path: /tmp/${{ env.ARTIFACT }}
          if-no-files-found: 'error'
          retention-days: 1
          compression-level: 0
          overwrite: true
          include-hidden-files: false
      - name: Step - flyctl Setup ᵛ⁰·³·¹⁶⁷
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLY_VERSION }}
      - name: Step - Push Go Artifact into Fly.io Volume
        env:
          ARTIFACT: ${{ steps.build_n_compress.outputs.artifact }}
        run: |
          HOSTNAME=$(flyctl status --app="$APP" --json | jq -r '.Hostname')
          curl -s -o /dev/null -w "%{http_code}" "https://$HOSTNAME" || true
          sleep 5
          flyctl ssh sftp shell --app="$APP" <<< "put /tmp/$ARTIFACT /gofiber/$ARTIFACT"
      - name: Step - Make Go Artifact Executable
        env:
          ARTIFACT: ${{ steps.build_n_compress.outputs.artifact }}
        run: flyctl ssh console --app="$APP" --command "chmod +x /gofiber/$ARTIFACT"
  job_fly_app_update:
    name: 🪂 Fly App Update
    needs: [job_build_push_go_artifact]
    if: ${{ inputs.fly_app_update }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Step - Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: '${{ github.repository }}'
          token: '${{ github.token }}'
      - name: Step - flyctl Setup ᵛ⁰·³·¹⁶⁷
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLY_VERSION }}
      - name: Step - Fly.io App Config Validate
        run: flyctl config validate --app="$APP" --config='./fly.io/go-fiber-app.toml' --strict --debug --verbose
      - name: Step - Get Fly.io Machine ID
        run: echo "VM_ID=$(flyctl machine list --app="$APP" --quiet)" >> $GITHUB_ENV
      - name: Step - Fly.io App Update
        env:
          IMAGE: docker.io/balajipothula/go:1.21
          ARTIFACT: ${{ needs.job_build_push_go_artifact.outputs.artifact }}
          SUPABASE_PG_HOST: ${{ vars.SUPABASE_PG_HOST }}
          SUPABASE_PG_PORT: ${{ vars.SUPABASE_PG_PORT }}
          SUPABASE_PG_DB_NAME: ${{ vars.SUPABASE_PG_DB_NAME }}
          SUPABASE_PG_USER: ${{ vars.SUPABASE_PG_USER }}
          SUPABASE_PG_PASSWORD: ${{ secrets.SUPABASE_PG_PASSWORD }}
        run: |
          flyctl machine update $VM_ID \
            --app="$APP" \
            --autostart \
            --autostop='stop' \
            --config='./fly.io/go-fiber-app.toml' \
            --detach \
            --entrypoint="/gofiber/$ARTIFACT" \
            --env SUPABASE_PG_HOST="$SUPABASE_PG_HOST" \
            --env SUPABASE_PG_PORT="$SUPABASE_PG_PORT" \
            --env SUPABASE_PG_DB_NAME="$SUPABASE_PG_DB_NAME" \
            --env SUPABASE_PG_USER="$SUPABASE_PG_USER" \
            --env SUPABASE_PG_PASSWORD="$SUPABASE_PG_PASSWORD" \
            --image="$IMAGE" \
            --port='443:3000/tcp:http:tls' \
            --yes
